# Generated by Django 3.1.4 on 2021-06-16 21:00

import company.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, validators=[company.validator.validate_phone]),
        ),
        migrations.AlterField(
            model_name='leadsmodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, validators=[company.validator.validate_phone]),
        ),
    ]
