# Generated by Django 3.1.4 on 2021-07-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210616_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='type',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='notes',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='leadsmodel',
            name='notes',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='leadsmodel',
            name='social_account',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='leadsmodel',
            name='type',
            field=models.CharField(blank=True, choices=[('lead', 'lead'), ('contact', 'contact')], max_length=52, null=True),
        ),
    ]
