# Generated by Django 3.1.4 on 2021-07-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20210704_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsmodel',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
