# Generated by Django 3.1.4 on 2021-07-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20210704_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='notes',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='leadsmodel',
            name='notes',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
