# Generated by Django 3.1.4 on 2021-07-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20210704_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leadsmodel',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leadsmodel',
            name='type',
            field=models.CharField(choices=[('lead', 'lead'), ('contact', 'contact')], default='lead', max_length=52),
        ),
    ]
