# Generated by Django 3.1.4 on 2021-07-04 22:08

import company.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20210704_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='mobile',
            field=models.CharField(max_length=20, validators=[company.validator.validate_phone]),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='notes',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='leadsmodel',
            name='mobile',
            field=models.CharField(max_length=20, validators=[company.validator.validate_phone]),
        ),
        migrations.AlterField(
            model_name='leadsmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leadsmodel',
            name='notes',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
