# Generated by Django 3.1.4 on 2021-05-10 04:30

import company.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[company.validator.validate_phone]),
        ),
    ]
