# Generated by Django 3.1.4 on 2021-05-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
