# Generated by Django 3.1.4 on 2021-05-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210512_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='ip_adress',
            new_name='ip_address',
        ),
    ]
