# Generated by Django 3.1.4 on 2021-05-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_log_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('add', 'add'), ('edit', 'edit'), ('delete', 'delete')], max_length=100),
        ),
    ]
