# Generated by Django 3.1.4 on 2021-05-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210516_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='record_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
