# Generated by Django 3.1.4 on 2021-07-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_product'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.product'),
        ),
        migrations.AddField(
            model_name='callmodel',
            name='about_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.product'),
        ),
        migrations.AddField(
            model_name='meetingmodel',
            name='about_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.product'),
        ),
        migrations.AddField(
            model_name='sendemailmodel',
            name='about_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.product'),
        ),
        migrations.AddField(
            model_name='whatsappmodel',
            name='about_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.product'),
        ),
    ]
