# Generated by Django 3.1.4 on 2021-07-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210703_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymodel',
            name='type',
            field=models.CharField(blank=True, choices=[('Call', 'Call'), ('Email', 'Email'), ('Whatsapp message', 'Whatsapp message'), ('Meeting', 'Meeting')], max_length=52, null=True),
        ),
    ]
