# Generated by Django 3.1.4 on 2021-07-04 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0009_auto_20210705_0008'),
        ('tasks', '0004_auto_20210704_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callmodel',
            name='about_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.product'),
        ),
        migrations.AlterField(
            model_name='callmodel',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contactmodel'),
        ),
        migrations.AlterField(
            model_name='meetingmodel',
            name='about_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.product'),
        ),
        migrations.AlterField(
            model_name='meetingmodel',
            name='details',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sendemailmodel',
            name='about_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.product'),
        ),
        migrations.AlterField(
            model_name='sendemailmodel',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contactmodel'),
        ),
        migrations.AlterField(
            model_name='sendemailmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='sendemailmodel',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='Assign_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contactmodel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='statue',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_type',
            field=models.CharField(choices=[('Call', 'Call'), ('Email', 'Email'), ('Whatsapp message', 'Whatsapp message'), ('Meet', 'Meet'), ('Reminder', 'Reminder')], max_length=52),
        ),
        migrations.AlterField(
            model_name='whatsappmodel',
            name='about_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.product'),
        ),
        migrations.AlterField(
            model_name='whatsappmodel',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
