# Generated by Django 3.1.4 on 2021-07-04 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20210705_0008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_auto_20210705_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callmodel',
            name='details',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='note',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='Assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.contactmodel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='statue',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('done', 'done')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_type',
            field=models.CharField(blank=True, choices=[('Call', 'Call'), ('Email', 'Email'), ('Whatsapp message', 'Whatsapp message'), ('Meet', 'Meet'), ('Reminder', 'Reminder')], max_length=52, null=True),
        ),
    ]
