# Generated by Django 3.1.4 on 2021-05-15 05:57

import company.validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('industry', models.CharField(blank=True, max_length=50)),
                ('company_owner', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('street', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(max_length=20, validators=[company.validator.validate_phone])),
                ('office_phone', models.CharField(max_length=20, validators=[company.validator.validate_phone])),
                ('fax', models.CharField(max_length=20, validators=[company.validator.validate_phone])),
                ('email', models.EmailField(max_length=30)),
                ('employees_numbers', models.IntegerField()),
                ('social_page', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
