# Generated by Django 3.1.4 on 2021-05-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='employees_numbers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='office_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='social_page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
