# Generated by Django 3.1.4 on 2021-05-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210531_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='office_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
